spring:
  application:
    name: picpay-backend-challenge
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/picpay_simplified
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/picpay_simplified
  threads:
    virtual:
      enabled: true

picpay-backend-challenge:
  transfer:
    authorization:
      host: ${TRANSFER_AUTHORIZATION_HOST}
      path: /api/v1/transfers/authorization
    notification:
      host: ${TRANSFER_NOTIFICATION_HOST}
      path: /api/v1/transfers/notification

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: [ "health", "loggers", "metrics", "prometheus" ]