spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/picpay_simplified
    username: root
    password: root
  flyway:
    user: root
    password: root
    url:  jdbc:postgresql://localhost:5432/picpay_simplified
  kafka:
    bootstrap-servers: localhost:9092
    ssl:
      key-store-location: ""
      key-password: ""
    security:
      protocol: PLAINTEXT

application:
  transfer:
    authorization:
      host: http://localhost:9090

logging:
  level:
    com.moura: trace